title: Your blog title here
description: Your blog description
author:
  # url is important, be sure replace url before deployment
  url: https://lume-blog-muse.pages.dev/
  name: Your User Name
  bio: Your bio here
  # recommended resolution: 512x512,1:1
  photoPath: /img/Sample_User_Icon.png
  # If you dont have social media just add # to comment that line.
  email: example@example.com
  twitter: https://example.com/
  youtube: https://example.com/
  github: https://example.com/
footer: Footer message here

friends: 
  - 
    name: friend1
    photoPath: /img/friends/Sample_User_Icon.png
    bio: My friend1
    link: https://www.friend1.com
  - 
    name: friend2
    photoPath: /img/friends/Sample_User_Icon.png
    bio: My friend2
    link: https://www.friend1.com

# How many posts in your archive page.
postsPerPage : 5
# How many posts in your main page.
indexPostNum : 5

# Enable dark mode according system settings.
autoDarkMode : true
# Use dark mode or light mode only, only available when autoDarkMode is false
# if value is false, use light theme only
# if value is true, dark theme only
darkMode : true

# Go https://disqus.com/admin/create/ create a new site
disqus: 
  enable: false
  # this is shortname of your disqus site
  # for example : the disqus site admin url is https://myblog.disqus.com/admin/
  # the short name is: myblog
  # detial:https://help.disqus.com/en/articles/1717111-what-s-a-shortname
  shortname: shortname

# Go https://dash.cloudflare.com/ -> Web Analytics. Get token in js Snippet.
cloudflareWebAnalytics:
  enable: false
  token: token

# Lume version this template should work.
# Check lume-blog-muse github repository to get template for newer lume.
version:
  lume: 0.25.5
  bulma: 0.9.3
